language: python
dist: trusty
branches:
  only:
  - master
  - "/^\\d\\.\\d+$/"
  - "/^\\d\\.\\d+\\.\\d+(rc\\d+|\\.dev\\d+)?$/"
matrix:
  include:
  - python: 2.7
    env: TOXENV=py27
  - python: 3.5
    env: TOXENV=py35
  - python: 3.6
    env: TOXENV=py36
  - python: 3.7
    env: TOXENV=py37
    dist: focal
    sudo: true
  - python: 3.8
    env: TOXENV=py38
    dist: focal
    sudo: true
  - python: 3.9
    env: TOXENV=py39
    dist: focal
    sudo: true
  - python: 3.10
    env: TOXENV=py310
    dist: focal
    sudo: true
  - python: 2.7
    env: TOXENV=pypy
  - python: 2.7
    env: TOXENV=pypy3
install:
- |
  if [ "$TOXENV" = "pypy" ]; then
    export PYPY_MAJOR_VERSION="pypy-7.2.0"
    export PYPY_VERSION="pypy-7.2.0-linux_x86_64-portable"
    wget "https://github.com/squeaky-pl/portable-pypy/releases/download/${PYPY_MAJOR_VERSION}/${PYPY_VERSION}.tar.bz2"
    tar -jxf ${PYPY_VERSION}.tar.bz2
    virtualenv --python="$PYPY_VERSION/bin/pypy" "$HOME/virtualenvs/$PYPY_VERSION"
    source "$HOME/virtualenvs/$PYPY_VERSION/bin/activate"
  fi
  if [ "$TOXENV" = "pypy3" ]; then
    export PYPY_MAJOR_VERSION="pypy3.6-7.2.0"
    export PYPY_VERSION="pypy3.6-7.2.0-linux_x86_64-portable"
    wget "https://github.com/squeaky-pl/portable-pypy/releases/download/${PYPY_MAJOR_VERSION}/${PYPY_VERSION}.tar.bz2"
    tar -jxf ${PYPY_VERSION}.tar.bz2
    virtualenv --python="$PYPY_VERSION/bin/pypy" "$HOME/virtualenvs/$PYPY_VERSION"
    source "$HOME/virtualenvs/$PYPY_VERSION/bin/activate"
  fi
- pip install -U codecov tox wheel
script: tox
after_success:
  - codecov
deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  user: anubhavp
  password:
    secure: bLB4MZIg6EdY3BysDbjNysufrvV6YpUZt6hOCWJ23HEiqsAIatvMAG1u8rkSoPLiYWuWsgeO+E18eu88LKc0GUvnUJjE5PB5ggt03dv7zSRcfhIo5othmxb65cRbAknL3vwaN8xzz6o6yAfrg1fapVwcWFnMxJgolmoB0nC0BQcpiUxrE8L9m56r+luWT6LhhSiSZdthCzJwi7OUV5NSDgYzxz2whgYXkrD3XxdDQgohYqwAzlThwGca/DOncntXOudlinf+g6fcBvNJf2lCwFls5sNg90H8XWub7J/xmG8bfXRTN5efIbP4KGaZR41wJHAl+CjgPVGsyy+vshDAwpmQLiBmoR04c6TYLpMg8idit3GMiWGGgtJGfeerl8WNeuyxGEXUrP5VJgM+9MVdknt1gMQgRVXk2TVKeFhakumqOMUsTTjrO8jEM/CwoRZpdhLupxagBaziXqM2VAEcSQYgiQ39xIZFSgobTG2IpCTU3kCUJobSmAOADBZMtfbFH/lmL+q5GAzf6h60GGmVVo424hv0HgDKEOuNLGnpXKeu8yVeE/QwgDkXSokBeKjiHqZBI7WD0rdY50B6aSvM2Zoo1UdygsitURnMvibKwg3rPc1tH082ZL+1ICgxp180yt6aXQj6yfl/CCA09qaAjy6eeNWR9fh50rFVvrkTNbU=
  on:
    tags: true
    repo: scrapy/protego
    condition: "$TOXENV == py39 && $TRAVIS_TAG =~ ^[0-9]+[.][0-9]+[.][0-9]+(rc[0-9]+|[.]dev[0-9]+)?$"
